version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ufcdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

  livescoring-service:
    build: ./livescoring-service
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/livescoringdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"

  narrative-service:
    build: ./narrative-service
    ports:
      - "5001:5001"

  stats-service:
    build: ./stats-service
    ports:
      - "5002:5002"

volumes:
  postgres-data:
