version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8083:8081"
    depends_on:
      mongo-db:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8081"

  livescoring-service:
    build: ./livescoring-service
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: ${LIVESCORING_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${LIVESCORING_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${LIVESCORING_SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8082"

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"

  narrative-service:
    build: ./narrative-service
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: ${MONGO_URI_NARRATIVE}
    ports:
      - "5001:5001"

  stats-service:
    build: ./stats-service
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: ${MONGO_URI_STATS}
    ports:
      - "5002:5002"

volumes:
  postgres-data:
  mongo-data:
